export const MY_ITEM_LOADER = 'MY_ITEM_LOADER';
export const MY_ITEM_SUCCESS = 'MY_ITEM_SUCCESS';
export const MY_ITEM_FAILED = 'MY_ITEM_FAILED';

export const DELETE_MY_ITEM_LOADER = 'DELETE_MY_ITEM_LOADER';
export const DELETE_MY_ITEM_SUCCESS = 'DELETE_MY_ITEM_SUCCESS';
export const DELETE_MY_ITEM_FAILED = 'DELETE_MY_ITEM_FAILED';